# Build-local adapter; never edit the SDK checkout. Preserve the object name
# used by IDF's esp_eth linker fragment to keep its hot functions in IRAM.
idf_component_get_property(eth_lib esp_eth COMPONENT_LIB)
idf_component_get_property(eth_dir esp_eth COMPONENT_DIR)
set(dma_source "${eth_dir}/src/mac/esp_eth_mac_esp_dma.c")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${dma_source}")
file(SHA256 "${dma_source}" dma_sha)
if(NOT dma_sha STREQUAL "f07a7291dbeea6529b128b40a4f0e617e42b55fba4aa6aef5fe2022402bd3076")
    message(FATAL_ERROR "S31 direct TX requires the validated IDF DMA source; review the adapter before updating IDF")
endif()
set(adapter "${CMAKE_CURRENT_BINARY_DIR}/s31_direct/esp_eth_mac_esp_dma.c")
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/s31_direct")
file(WRITE "${adapter}" "#include \"esp_attr.h\"\n#include \"esp_private/eth_mac_esp_dma.h\"\nuint32_t IRAM_ATTR s31_emac_transmit_frame_copy(emac_esp_dma_handle_t, uint8_t *, uint32_t);\nuint32_t IRAM_ATTR s31_emac_transmit_frame_ext_copy(emac_esp_dma_handle_t, emac_esp_dma_transmit_buff_t *, uint32_t, eth_mac_time_t *);\n#define emac_esp_dma_transmit_frame_ext s31_emac_transmit_frame_ext_copy\n#define emac_esp_dma_transmit_frame s31_emac_transmit_frame_copy\n#include \"${dma_source}\"\n#undef emac_esp_dma_transmit_frame_ext\n#undef emac_esp_dma_transmit_frame\n#include \"${CMAKE_CURRENT_LIST_DIR}/emac_direct.inc\"\n")
get_target_property(eth_sources ${eth_lib} SOURCES)
set(replaced FALSE)
foreach(src IN LISTS eth_sources)
    if(src MATCHES "(^|/)esp_eth_mac_esp_dma\\.c$")
        list(REMOVE_ITEM eth_sources "${src}")
        list(APPEND eth_sources "${adapter}")
        set(replaced TRUE)
        break()
    endif()
endforeach()
if(NOT replaced)
    message(FATAL_ERROR "S31 direct TX could not find the IDF DMA source")
endif()
set_property(TARGET ${eth_lib} PROPERTY SOURCES "${eth_sources}")
